[general]
live_config_reload = true
import = ["themes/themes/iterm.toml"]
# import = ["themes/themes/monokai_charcoal.toml"]
# import = ["themes/themes/gruvbox_material.toml"]
# import = ["themes/themes/ayu_dark.toml"]

[env]
# TERM = "alacritty"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.7

[scrolling]
history = 16384

[font]
builtin_box_drawing = false
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
